#!/bin/bash
#
#  Copyright (C) 2020 Gaël PORTAY
#
#  SPDX-License-Identifier: LGPL-2.1
#

ls_orphans() {
	cat <<EOF | sqlite3 fs.db
SELECT path FROM files WHERE parent NOT IN (SELECT path FROM files);
EOF
}

mkdir_lost_found() {
	timestamp="$(date "+%s")"
	cat <<EOF | sqlite3 fs.db
INSERT OR IGNORE INTO files(path, parent, 
st_dev, st_ino, st_mode, st_nlink, st_uid, st_gid, st_rdev,
st_size, st_blksize, st_blocks, st_atim_sec, st_atim_nsec,
st_mtim_sec, st_mtim_nsec, st_ctim_sec, st_ctim_nsec)
VALUES("/.lost+found", "/", 0, 0, 16877, 2, $UID, $UID, 0, 0, 0, 0,
$timestamp, 0, $timestamp, 0, $timestamp, 0);
EOF
}

mv_lost_found() {
	echo "$1 -> /.lost+found/${1##*/}"
	cat <<EOF | sqlite3 fs.db
UPDATE files SET path="/.lost+found/${1##*/}", parent="/.lost+found" WHERE path="$1";
EOF
}

mkdir_lost_found
mapfile -t orphans < <(ls_orphans)
for orphan in "${orphans[@]}"
do
	mv_lost_found "$orphan"
done
