= sqlitefs(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com
:lang: en
:man manual: SQLiteFS FUSE module manual
:man source: sqlitefs

== NAME

sqlitefs - example of how to use FUSE using in a SQLite database filesystem

== SYNOPSIS

*sqlitefs* [OPTIONS] MOUNTPOINT

== DESCRIPTION

*sqlitefs(1)* mounts a virtual filesystem based on SQLite a in Userspace using
FUSE.

== OPTIONS

FUSE options:

**-h --help**::
	print help

**-V --version**::
	print version

**-d -o debug**::
	enable debug output (implies -f)

**-f**::
	foreground operation

**-s**::
	disable multi-threaded operation

**-o clone_fd**::
	use separate fuse device fd for each thread (may improve performance)

**-o max_idle_threads**::
	the maximum number of idle worker threads allowed (default: 10)

**-o kernel_cache**
	cache files in kernel

**-o [no]auto_cache**
	enable caching based on modification times (off)

**-o umask=M**::
	set file permissions (octal)

**-o uid=N**::
	set file owner

**-o gid=N**::
	set file group

**-o entry_timeout=T**::
	cache timeout for names (1.0s)

**-o negative_timeout=T**::
	cache timeout for deleted names (0.0s)

**-o attr_timeout=T**::
	cache timeout for attributes (1.0s)

**-o ac_attr_timeout=T**::
	auto cache timeout for attributes (attr_timeout)

**-o noforget**::
	never forget cached inodes

**-o remember=T**::
	remember cached inodes for T seconds (0s)

**-o modules=M1[:M2...]**::
	names of modules to push onto filesystem stack

**-o allow_other**::
	allow access by all users

**-o allow_root**::
	allow access by root

**-o auto_unmount**::
	auto unmount on process termination

Options for subdir module:

**-o subdir=DIR**::
	prepend this directory to all paths (mandatory)

**-o [no]rellinks**::
	transform absolute symlinks to relative

Options for iconv module:

**-o from_code=CHARSET**::
	original encoding of file names (default: UTF-8)

**-o to_code=CHARSET**::
	new encoding of the file names (default: UTF-8)

== AUTHOR

Written by Gaël PORTAY *gael.portay@gmail.com*

== COPYRIGHT

Copyright (C) 2018-2020 Gaël PORTAY

Copyright (C) 2018 Savoir-Faire Linux Inc.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation, either version 2.1 of the License, or (at your option) any
later version.

== SEE ALSO

sqlite3(1), fusermount(1)
